language: ruby
rvm:
  - 2.4.1

sudo: required

services:
  - docker
  - redis-server

cache: bundler

env:
  - DB=mysql

before_install:
  - docker build -t datacite/volpino .
  - docker run datacite/volpino /bin/sh -c "bundle exec rake test"

before_script:
  - memcached -p 11211 &
  - cp .env.travis .env
  - mkdir -p tmp/pids
  - mkdir -p log
  - cd vendor && npm install
  - cd ../ && npm install -g istanbul codeclimate-test-reporter
  - bundle exec rake db:setup RAILS_ENV=test
  - bundle exec sidekiq -d -e production --config config/sidekiq.yml -L log/sidekiq.log

script:
  - docker run datacite/volpino /bin/sh -c "bundle exec rspec"

addons:
  code_climate:
    repo_token: 8c899becf0595e2aeef04e628dc3d9e352f1d7ac9f6ef56b0ca8577c546bac90

notifications:
  slack: datacite:Wt8En0ALoTA6Kjc5EOKNDWxN
  email: false
