language: ruby
rvm:
  - 2.4.1

sudo: required

services:
  - docker
  - redis-server

cache: bundler

before_install:
  - docker build -t datacite/volpino .

script:
  - docker run datacite/volpino /bin/sh -c "bundle exec rspec"

addons:
  code_climate:
    repo_token: 8c899becf0595e2aeef04e628dc3d9e352f1d7ac9f6ef56b0ca8577c546bac90

notifications:
  slack: datacite:Wt8En0ALoTA6Kjc5EOKNDWxN
  email: false
