version: '2'

services:
  profiles:
    env_file: .env
    image: datacite/volpino
    ports:
      - "8080:80"
    volumes:
      - ./app:/home/app/webapp/app
      - ./config:/home/app/webapp/config
      - ./db:/home/app/webapp/db
      - ./spec:/home/app/webapp/spec
      - ./lib/seeds:/home/app/webapp/lib/seeds
      - ./vendor/docker:/home/app/webapp/vendor/docker
    networks:
      - public
  mysql:
    environment:
      MYSQL_DATABASE: datacite
      MYSQL_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    image: mysql:5.7
    ports:
      - "3311:3306"
    networks:
      - public
  redis:
    image: redis
    networks:
      - public
  memcached:
    image: memcached:1.4.31
    networks:
      - public
networks:
  public:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.0.60.0/24
        gateway: 10.0.60.1
