services:
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=datacite
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "3311:3306"
    networks:
      - public

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.18
    ports:
      - "9202:9200"
      - "9302:9300"
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      ELASTIC_PASSWORD: changeme
      xpack.security.enabled: "false"
      http.cors.enabled: "true"
      http.cors.allow-origin: "*"
    networks:
      - public
    healthcheck:
      test: curl -f http://localhost:9200 || exit 1
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - public

  memcached:
    image: memcached:1.4.31
    platform: linux/amd64  # ensures M1 Mac compatibility
    ports:
      - "11211:11211"
    networks:
      - public

networks:
  public:
    driver: bridge
