version: '2'

# when sharing the host folder, you need to reinstall Ruby gems
# and npm modules into the vendor folder

services:
  profiles:
    env_file: .env
    image: datacite/volpino
    ports:
      - "8080:80"
    volumes:
      - ./app:/home/app/webapp/app
      - ./config:/home/app/webapp/config
      - ./db:/home/app/webapp/db
      - ./spec:/home/app/webapp/spec
      - ./lib/seeds:/home/app/webapp/lib/seeds
      - ./vendor/docker:/home/app/webapp/vendor/docker
  db:
    env_file: .env
    image: mysql:5.6
    ports:
      - "3307:3306"
  redis:
    image: redis:2.8
  memcached:
    image: memcached:1.4.31
