mysql: &mysql
  adapter: mysql2

defaults: &defaults
  pool: <%= ENV['CONCURRENCY'].to_i + 5 %>
  timeout: 5000
  encoding: utf8mb4
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] || "127.0.0.1" %>
  port: <%= ENV['DB_PORT'] || 3306 %>

  <<: *<%= ENV['DB'] || "mysql" %>

development:
  <<: *defaults

test:
  <<: *defaults
  database: <%= ENV['DB_NAME'] %>_test

production:
  <<: *defaults

stage:
  <<: *defaults
