mysql: &mysql
  adapter: mysql2

defaults: &defaults
  pool: <%= ENV['CONCURRENCY'].to_i + 5 %>
  timeout: 5000
  encoding: utf8mb4
  database: <%= ENV['MYSQL_DATABASE'] %>
  username: <%= ENV['MYSQL_USER'] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>
  host: <%= ENV['MYSQL_HOST'] %>
  port: <%= ENV['MYSQL_PORT'] %>

  <<: *mysql

development:
  <<: *defaults

test:
  <<: *defaults
  database: <%= ENV['DB_NAME'] %>_test

production:
  <<: *defaults

stage:
  <<: *defaults
