# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12d577d94c15e666b3f7b2f78751df14a4e3c26421f57f77eb83b0dabeca78d9b0178b1df63627c2895575a0ca29a757c6c1337d88c64d3f81bf1a0f0f9510ba

test:
  secret_key_base: 5ff72200bed4ad9d0994b81862384bf17c6b9be5675de8d5be45448edcc45a5dca2a67527207e012714e098e7e158edefda045e6262de8da6c5aa7229aefb20f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
